[tool.poetry]
name = "dataproduct-apps"
version = "0.1.0"
description = "Dataproduct listing apps in clusters"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-bigquery = "1.28.0"
Flask = "^2.0.2"
fiaas-logging = "^0.1.1"
kafka-python = "^2.0.2"
k8s = "^0.19.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
prospector = "^1.5.1"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"

[tool.poetry.scripts]
dataproduct-apps-collect = "dataproduct_apps.main:collect"
dataproduct-apps-persist = "dataproduct_apps.main:persist"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
