[tool.poetry]
name = "dataproduct-apps"
version = "0.1.0"
description = "Dataproduct listing apps in clusters"
authors = ["NAIS <aura@nav.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-bigquery = "1.28.0"
Flask = "^2.0.2"
fiaas-logging = "^0.1"
kafka-python = "^2.0.2"
k8s = "^0.21"

[tool.poetry.dev-dependencies]
pytest = "^6"
prospector = "^1"
pytest-cov = "^3"
pytest-sugar = "^0.9"

[tool.poetry.scripts]
dataproduct-apps-collect = "dataproduct_apps.main:collect"
dataproduct-apps-persist = "dataproduct_apps.main:persist"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
