[tool.poetry]
name = "dataproduct-apps"
version = "0.1.0"
description = "Dataproduct listing apps in clusters"
authors = ["NAIS <aura@nav.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"
google-cloud-bigquery = "3.14.1"
google-cloud-storage = "2.14.0"
Flask = "^3.0.0"
fiaas-logging = "^0.1"
kafka-python = "^2.0.2"
k8s = "^0.23"

[tool.poetry.dev-dependencies]
pytest = "^7"
prospector = "^1"
pytest-cov = "^4"
pytest-sugar = "^0.9"

[tool.poetry.scripts]
dataproduct-apps-topics = "dataproduct_apps.main:topics"
dataproduct-apps-collect = "dataproduct_apps.main:collect"
dataproduct-apps-persist = "dataproduct_apps.main:persist"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
