[tool.poetry]
name = "dataproduct-apps"
version = "0.1.0"
description = "Dataproduct listing apps in clusters"
authors = ["NAIS <aura@nav.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"
google-cloud-bigquery = "3.25.0"
google-cloud-storage = "2.18.2"
Flask = "^3.0.3"
fiaas-logging = "^0.1"
kafka-python = "^2.0.2"
k8s = "^0.27"

[tool.poetry.dev-dependencies]
pytest = "^8"
prospector = "^1"
pytest-cov = "^5"
pytest-sugar = "^1.0"

[tool.poetry.scripts]
dataproduct-apps-topics = "dataproduct_apps.main:topics"
dataproduct-apps-collect = "dataproduct_apps.main:collect"
dataproduct-apps-persist = "dataproduct_apps.main:persist"

[tool.poetry.group.sbom-tools.dependencies]
cyclonedx-bom = "^4.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
