apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dataproduct-apps-persist
  namespace: aura
  labels:
    team: aura
spec:
  image: "{{ image }}"
  command:
    - dataproduct-apps-persist
  replicas:
    disableAutoScaling: true
    max: 1
    min: 1
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  kafka:
    pool: nav-infrastructure
