apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-apps-persist
  namespace: aura
  labels:
    team: aura
spec:
  image: "{{ image }}"
  command:
    - dataproduct-apps-persist
  schedule: "43 4 * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  kafka:
    pool: nav-infrastructure
  gcp:
    bigQueryDatasets:
      - name: dataproduct_apps
        permission: READWRITE
        description: "Applikasjoner som kjører i de forskjellige NAIS clusterne, med team og namespace"