apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-apps-topics
  namespace: nais
  labels:
    team: nais
spec:
  image: "{{ image }}"
  command:
    - dataproduct-apps-topics
  schedule: "45 3 * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  gcp:
    buckets:
      - name: dataproduct-apps-topics2