apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-apps-topics
  namespace: aura
  labels:
    team: aura
    apiserver-access: enabled
spec:
  image: "{{ image }}"
  command:
    - dataproduct-apps-topics
  schedule: "45 3 * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  kafka:
    pool: nav-infrastructure
