apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-apps-collect
  namespace: nais
  labels:
    team: nais
spec:
  image: "{{ image }}"
  command:
    - dataproduct-apps-collect
  schedule: "13 4 * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  kafka:
    pool: nav-infrastructure
