apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-apps
  namespace: aura
  labels:
    team: aura
spec:
  image: {{ image }}
  schedule: "13 4 * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  kafka:
    pool: nav-infrastructure
