apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: dataproduct-apps-collect
  name: dataproduct-apps-collect-apiserver
  namespace: aura
spec:
  egress:
  - to:
    - ipBlock:
        cidr: "{{ apiserver_cidr }}"
  podSelector:
    matchLabels:
      app: dataproduct-apps-collect
  policyTypes:
  - Egress

