name: Build and deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

env:
  DEPLOY_SERVER: deploy.nav.cloud.nais.io:443

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run linter and tests
        run: poetry run prospector && poetry run pytest

  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nais
          project_id: nais-management-233d
          identity_provider: projects/898056957967/locations/global/workloadIdentityPools/nav-identity-pool/providers/github-oidc-provider

  deploy-topics:
    name: Deploy Topic collector
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        cluster:
          - dev-gcp
          - prod-gcp
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy topic collector
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/naisjob-topics.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          DEPLOY_SERVER: ${{ env.DEPLOY_SERVER }}

  deploy-collector-gcp:
    name: Deploy Collector (GCP)
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        cluster:
          - dev-gcp
          - prod-gcp
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy to ${{ matrix.cluster }}
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/naisjob-collect-gcp.yaml,nais/prometheusrule-collect.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          DEPLOY_SERVER: ${{ env.DEPLOY_SERVER }}

  deploy-collector-onprem:
    name: Deploy Collector (on-prem)
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        cluster:
          - dev-fss
          - prod-fss
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy to ${{ matrix.cluster }}
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/naisjob-collect-onprem.yaml,nais/prometheusrule-collect.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          DEPLOY_SERVER: ${{ env.DEPLOY_SERVER }}

  deploy-other:
    name: Deploy Persist and Topics
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy persist application to prod-gcp (nais namespace)
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/naisjob-persist.yaml,nais/prometheusrule-persist.yaml,nais/topics.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          DEPLOY_SERVER: ${{ env.DEPLOY_SERVER }}
